"""Generate immutable build provenance inside wheels and source archives.

The generated JSON is force-included from a temporary path, so a build never
changes the source checkout it is claiming.  A wheel built from our sdist
inherits the sdist's already-verified source anchors and changes only the
artifact type and its derived build ID.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

FIELDS = {
    "provenance_schema_version",
    "artifact_type",
    "source_revision",
    "source_date_epoch",
    "source_dirty",
    "dependency_lock_sha256",
    "release_identity_sha256",
    "build_id",
}


def _canonical(value: dict[str, Any]) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _run_git(root: Path, *args: str) -> str:
    result = subprocess.run(["git", *args], cwd=root, check=True, capture_output=True, text=True)
    return result.stdout.strip()


def _validate_carried(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != FIELDS:
        raise RuntimeError("carried build provenance has an invalid field set")
    base = dict(value)
    claimed = base.pop("build_id", None)
    if claimed != hashlib.sha256(_canonical(base)).hexdigest():
        raise RuntimeError("carried build provenance has an invalid build ID")
    if base.get("source_dirty") is not False:
        raise RuntimeError("release artifacts cannot inherit dirty source provenance")
    return dict(value)


def provenance_payload(root: Path, artifact_type: str) -> dict[str, Any]:
    """Return deterministic provenance for ``artifact_type``.

    ``root`` is either the clean Git checkout or an unpacked HawaVoClean
    sdist containing the provenance generated by its own build.
    """
    carried_path = root / "src" / "hawavoclean" / "build-provenance.json"
    if carried_path.is_file() and not (root / ".git").exists():
        carried = _validate_carried(json.loads(carried_path.read_text(encoding="utf-8")))
        base = {key: value for key, value in carried.items() if key != "build_id"}
        base["artifact_type"] = artifact_type
    else:
        status = _run_git(root, "status", "--porcelain", "--untracked-files=normal")
        if status:
            raise RuntimeError(
                "refusing to build release artifacts from a dirty source tree; "
                "commit or remove every change first"
            )
        revision = _run_git(root, "rev-parse", "HEAD")
        if len(revision) != 40:
            raise RuntimeError("Git did not return a full source revision")
        lock_path = root / "uv.lock"
        release_path = root / "src" / "hawavoclean" / "release.json"
        if not lock_path.is_file() or not release_path.is_file():
            raise RuntimeError("release build requires uv.lock and packaged release.json")
        base = {
            "provenance_schema_version": 1,
            "artifact_type": artifact_type,
            "source_revision": revision,
            "source_date_epoch": int(_run_git(root, "show", "-s", "--format=%ct", "HEAD")),
            "source_dirty": False,
            "dependency_lock_sha256": _sha256(lock_path),
            "release_identity_sha256": _sha256(release_path),
        }
    value = dict(base)
    value["build_id"] = hashlib.sha256(_canonical(base)).hexdigest()
    return value


class CustomBuildHook(BuildHookInterface):
    """Inject build provenance into both Hatch targets."""

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        # Editable installs execute against the checkout and are described at
        # runtime as ``source-tree``; they are not release artifacts and must
        # remain usable while a developer has uncommitted work.
        if version == "editable":
            return
        root = Path(self.root).resolve()
        target = str(self.target_name)
        value = provenance_payload(root, target)
        encoded = json.dumps(value, indent=2, sort_keys=True).encode("utf-8") + b"\n"
        carried_path = root / "src" / "hawavoclean" / "build-provenance.json"

        # When Hatch is building a wheel from an unpacked sdist, this is an
        # ephemeral source tree and the carried file is already selected as
        # package data. Updating it avoids a duplicate force-include mapping.
        if carried_path.is_file() and not (root / ".git").exists():
            carried_path.write_bytes(encoded)
            return

        temp_dir = Path(tempfile.mkdtemp(prefix="hawavoclean-provenance-"))
        generated = temp_dir / "build-provenance.json"
        generated.write_bytes(encoded)
        destination = (
            "src/hawavoclean/build-provenance.json"
            if target == "sdist"
            else "hawavoclean/build-provenance.json"
        )
        build_data["force_include"][str(generated)] = destination
