"""Fail-closed Smart Safe analysis, eligibility, and ranking contracts."""

from hawavoclean.smart_safe.analyzer import (
    DEFAULT_ANALYZER_CONFIG,
    AnalyzerConfig,
    ProbabilityEstimate,
    StreamingAcousticAnalyzer,
    StreamingAcousticReport,
    analyze_audio_stream,
)
from hawavoclean.smart_safe.calibration import (
    CalibrationMetrics,
    RouteRegretSummary,
    TemperatureCalibrator,
    compute_expected_calibration_error,
    compute_route_regret,
    verify_abstention_and_tie_properties,
)
from hawavoclean.smart_safe.decision import (
    RESTORE_ROUTES,
    ROUTES,
    AcousticEvidence,
    CandidateEvidence,
    CandidateOutcome,
    RegionRecommendation,
    RestorePolicy,
    Route,
    SmartSafeDecision,
    SmartSafePolicy,
    SmartSafeRanker,
    UnqualifiedRankerError,
    decide_smart_safe,
    eligible_routes,
    stabilize_region_routes,
)
from hawavoclean.smart_safe.preview import (
    CandidatePreview,
    SmartSafePreviewEngine,
    abstain_to_least_intervention,
    compute_evidence_sha256,
    extract_preview_slice,
    verify_candidate_evidence_integrity,
    verify_post_master_invariants,
)
from hawavoclean.smart_safe.region import (
    RegionalAssemblyResult,
    filter_region_routes_for_acoustics,
    render_and_stitch_regions,
)

__all__ = [
    "RESTORE_ROUTES",
    "ROUTES",
    "AcousticEvidence",
    "AnalyzerConfig",
    "CalibrationMetrics",
    "CandidateEvidence",
    "CandidateOutcome",
    "CandidatePreview",
    "DEFAULT_ANALYZER_CONFIG",
    "ProbabilityEstimate",
    "RegionRecommendation",
    "RegionalAssemblyResult",
    "RestorePolicy",
    "Route",
    "RouteRegretSummary",
    "SmartSafeDecision",
    "SmartSafePolicy",
    "SmartSafePreviewEngine",
    "SmartSafeRanker",
    "StreamingAcousticAnalyzer",
    "StreamingAcousticReport",
    "TemperatureCalibrator",
    "UnqualifiedRankerError",
    "abstain_to_least_intervention",
    "analyze_audio_stream",
    "compute_evidence_sha256",
    "compute_expected_calibration_error",
    "compute_route_regret",
    "decide_smart_safe",
    "eligible_routes",
    "extract_preview_slice",
    "filter_region_routes_for_acoustics",
    "render_and_stitch_regions",
    "stabilize_region_routes",
    "verify_abstention_and_tie_properties",
    "verify_candidate_evidence_integrity",
    "verify_post_master_invariants",
]
